### ISSUE TITLE
MissingSecretError

### ISSUE THREAD

**Issue by Entheologian** [kyoheiu/hmstr#27]
Using this config I get the error below:
```
version: "3"
services:
  server:
    image: docker.io/kyoheiudev/leaf-server:0.3.7
    container_name: server
    volumes:
      - ./server/databases:/var/leaf/databases
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9000:8000
  client:
    image: docker.io/kyoheiudev/leaf-client:0.3.7
    container_name: client
    volumes:
      - ./client/.env.production:/app/.env.production
    ports:
      - 4000:3000
```

```
server    | 2023-04-05T09:22:48.314930Z  INFO tantivy::directory::file_watcher: Meta file "/var/leaf/databases/.search/meta.json" was modified    
client    | yarn run v1.22.19
client    | $ next start
client    | ready - started server on 0.0.0.0:3000, url: http://localhost:3000
client    | warn  - You have enabled experimental feature (scrollRestoration) in next.config.js.
client    | warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
client    | 
client    | [next-auth][error][NO_SECRET] 
client    | https://next-auth.js.org/errors#no_secret
client    | [next-auth][error][NO_SECRET] 
client    | https://next-auth.js.org/errors#no_secret Please define a `secret` in production. MissingSecret [MissingSecretError]: Please define a `secret` in production.
client    |     at assertConfig (/app/node_modules/next-auth/core/lib/assert.js:42:12)
client    |     at AuthHandler (/app/node_modules/next-auth/core/index.js:70:52)
client    |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
client    |     at async NextAuthHandler (/app/node_modules/next-auth/next/index.js:24:19)
client    |     at async /app/node_modules/next-auth/next/index.js:60:32
client    |     at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:372:9)
client    |     at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:514:9)
client    |     at async Object.fn (/app/node_modules/next/dist/server/next-server.js:828:35)
client    |     at async Router.execute (/app/node_modules/next/dist/server/router.js:243:32)
client    |     at async NextNodeServer.runImpl (/app/node_modules/next/dist/server/base-server.js:432:29) {
client    |   code: 'NO_SECRET'
client    | }
```

Is there something I need to change?
